"use client"

import { useState, useEffect } from "react"
import {
    Droplet, Plus, Edit, Trash2, Loader2, RefreshCw, Save, X, CheckCircle,
    XCircle, Palette, DollarSign
} from "lucide-react"
import { DashboardLayout } from "@/components/layout/dashboard-layout"
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { toast } from "@/components/ui/toast"
import { formatCurrency } from "@/lib/utils"
import { supabase, isSupabaseConfigured } from "@/lib/supabase"

// Fuel Type interface matching database schema
interface FuelType {
    fuel_type_id: number
    fuel_name: string
    fuel_code: string
    description: string | null
    price_per_liter: number
    color_code: string
    is_active: boolean
    created_at: string
}

// Generate fuel type code like FT01, FT02, etc.
function generateFuelCode(count: number): string {
    const nextNum = count + 1
    const paddedNum = nextNum.toString().padStart(2, "0")
    return `FT${paddedNum}`
}

// Fuel Type Form Modal
function FuelTypeFormModal({
    fuelType,
    nextFuelTypeNumber,
    onSave,
    onClose,
}: {
    fuelType: FuelType | null
    nextFuelTypeNumber: number
    onSave: (data: Partial<FuelType>) => Promise<void>
    onClose: () => void
}) {
    const isEditing = !!fuelType
    const [loading, setLoading] = useState(false)
    const autoGeneratedCode = isEditing ? fuelType.fuel_code : generateFuelCode(nextFuelTypeNumber)
    const [formData, setFormData] = useState({
        fuel_code: autoGeneratedCode,
        fuel_name: fuelType?.fuel_name || "",
        description: fuelType?.description || "",
        price_per_liter: fuelType?.price_per_liter || 0,
        color_code: fuelType?.color_code || "#3B82F6",
        is_active: fuelType?.is_active ?? true,
    })

    // Predefined colors for easy selection
    const colorOptions = [
        { name: "Green", value: "#10B981" },
        { name: "Yellow", value: "#F59E0B" },
        { name: "Blue", value: "#3B82F6" },
        { name: "Purple", value: "#8B5CF6" },
        { name: "Red", value: "#EF4444" },
        { name: "Cyan", value: "#06B6D4" },
        { name: "Pink", value: "#EC4899" },
        { name: "Orange", value: "#F97316" },
    ]

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault()
        if (!formData.fuel_name) {
            toast.error("Error", "Fuel name is required")
            return
        }
        if (formData.price_per_liter <= 0) {
            toast.error("Error", "Price per liter must be greater than 0")
            return
        }
        setLoading(true)
        try {
            await onSave(formData)
            onClose()
        } catch (error: unknown) {
            const errorMessage = error instanceof Error ? error.message : "Failed to save"
            toast.error("Error", errorMessage)
        }
        setLoading(false)
    }

    return (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
            <div className="bg-white rounded-2xl shadow-2xl w-full max-w-md">
                <div className="p-6 border-b border-gray-100">
                    <div className="flex items-center justify-between">
                        <h2 className="text-xl font-bold text-gray-900 flex items-center gap-2">
                            {isEditing ? <Edit className="w-5 h-5 text-blue-600" /> : <Plus className="w-5 h-5 text-green-600" />}
                            {isEditing ? "✏️ Edit Fuel Type" : "➕ Add New Fuel Type"}
                        </h2>
                        <button onClick={onClose} className="p-2 hover:bg-gray-100 rounded-lg">
                            <X className="w-5 h-5 text-gray-500" />
                        </button>
                    </div>
                </div>

                <form onSubmit={handleSubmit} className="p-6 space-y-4">
                    {/* Fuel Code */}
                    <div>
                        <label className="block text-sm font-semibold text-gray-700 mb-2">🏷️ Fuel Code (Auto)</label>
                        <input
                            type="text"
                            value={formData.fuel_code}
                            readOnly
                            className="w-full px-4 py-3 border-2 border-gray-200 rounded-xl bg-gray-100 text-gray-600 cursor-not-allowed"
                        />
                        <p className="text-xs text-gray-500 mt-1">Auto-generated</p>
                    </div>

                    {/* Fuel Name */}
                    <div>
                        <label className="block text-sm font-semibold text-gray-700 mb-2">⛽ Fuel Name *</label>
                        <input
                            type="text"
                            value={formData.fuel_name}
                            onChange={(e) => setFormData({ ...formData, fuel_name: e.target.value })}
                            placeholder="e.g., Super Petrol, Diesel, Kerosene"
                            className="w-full px-4 py-3 border-2 border-gray-200 rounded-xl focus:border-blue-500 outline-none"
                            required
                        />
                    </div>

                    {/* Description */}
                    <div>
                        <label className="block text-sm font-semibold text-gray-700 mb-2">📝 Description</label>
                        <input
                            type="text"
                            value={formData.description}
                            onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                            placeholder="Brief description"
                            className="w-full px-4 py-3 border-2 border-gray-200 rounded-xl focus:border-blue-500 outline-none"
                        />
                    </div>

                    {/* Price per Liter */}
                    <div>
                        <label className="block text-sm font-semibold text-gray-700 mb-2">💰 Price per Liter (KES) *</label>
                        <input
                            type="number"
                            step="0.01"
                            value={formData.price_per_liter}
                            onChange={(e) => setFormData({ ...formData, price_per_liter: parseFloat(e.target.value) || 0 })}
                            placeholder="e.g., 180.50"
                            className="w-full px-4 py-3 border-2 border-gray-200 rounded-xl focus:border-blue-500 outline-none"
                            required
                        />
                    </div>

                    {/* Color Selection */}
                    <div>
                        <label className="block text-sm font-semibold text-gray-700 mb-2">🎨 Display Color</label>
                        <div className="grid grid-cols-4 gap-2 mb-2">
                            {colorOptions.map((color) => (
                                <button
                                    key={color.value}
                                    type="button"
                                    onClick={() => setFormData({ ...formData, color_code: color.value })}
                                    className={`w-full h-10 rounded-lg border-2 transition-all ${formData.color_code === color.value
                                            ? "border-gray-900 scale-110 shadow-lg"
                                            : "border-transparent hover:border-gray-300"
                                        }`}
                                    style={{ backgroundColor: color.value }}
                                    title={color.name}
                                />
                            ))}
                        </div>
                        <div className="flex items-center gap-2">
                            <input
                                type="color"
                                value={formData.color_code}
                                onChange={(e) => setFormData({ ...formData, color_code: e.target.value })}
                                className="w-10 h-10 rounded-lg cursor-pointer"
                            />
                            <span className="text-sm text-gray-500">Or pick custom color</span>
                        </div>
                    </div>

                    {/* Active Status */}
                    <div className="flex items-center justify-between p-4 bg-gray-50 rounded-xl">
                        <div>
                            <p className="font-semibold text-gray-900">🟢 Active Status</p>
                            <p className="text-sm text-gray-500">Enable or disable this fuel type</p>
                        </div>
                        <label className="relative inline-flex items-center cursor-pointer">
                            <input
                                type="checkbox"
                                checked={formData.is_active}
                                onChange={(e) => setFormData({ ...formData, is_active: e.target.checked })}
                                className="sr-only peer"
                            />
                            <div className="w-14 h-7 bg-gray-300 peer-focus:ring-4 peer-focus:ring-blue-300 rounded-full peer peer-checked:after:translate-x-full peer-checked:bg-green-500 after:content-[''] after:absolute after:top-0.5 after:left-[4px] after:bg-white after:rounded-full after:h-6 after:w-6 after:transition-all"></div>
                        </label>
                    </div>

                    {/* Preview */}
                    <div className="p-4 rounded-xl border-2 border-dashed border-gray-200">
                        <p className="text-xs text-gray-500 mb-2">Preview:</p>
                        <div className="flex items-center gap-3">
                            <div
                                className="w-12 h-12 rounded-xl flex items-center justify-center"
                                style={{ backgroundColor: formData.color_code + "20" }}
                            >
                                <Droplet className="w-6 h-6" style={{ color: formData.color_code }} />
                            </div>
                            <div>
                                <p className="font-semibold">{formData.fuel_name || "Fuel Name"}</p>
                                <p className="text-sm text-gray-500">{formatCurrency(formData.price_per_liter)}/L</p>
                            </div>
                        </div>
                    </div>

                    {/* Actions */}
                    <div className="flex gap-3 pt-4">
                        <Button type="button" variant="outline" onClick={onClose} className="flex-1">
                            <X className="w-4 h-4" /> Cancel
                        </Button>
                        <Button type="submit" loading={loading} className="flex-1">
                            <Save className="w-4 h-4" /> {isEditing ? "Update" : "Create"}
                        </Button>
                    </div>
                </form>
            </div>
        </div>
    )
}

// Main Fuel Types Page
export default function FuelTypesPage() {
    const [fuelTypes, setFuelTypes] = useState<FuelType[]>([])
    const [loading, setLoading] = useState(true)
    const [searchQuery, setSearchQuery] = useState("")
    const [showFormModal, setShowFormModal] = useState(false)
    const [selectedFuelType, setSelectedFuelType] = useState<FuelType | null>(null)

    useEffect(() => {
        fetchFuelTypes()
    }, [])

    const fetchFuelTypes = async () => {
        setLoading(true)
        try {
            if (isSupabaseConfigured() && supabase) {
                const { data, error } = await supabase
                    .from("fuel_types")
                    .select("*")
                    .order("fuel_name")

                if (error) throw error
                setFuelTypes(data || [])
            } else {
                toast.error("Database not configured", "Please configure Supabase")
                setFuelTypes([])
            }
        } catch (error) {
            console.error("Error fetching fuel types:", error)
            toast.error("Error", "Failed to load fuel types")
            setFuelTypes([])
        }
        setLoading(false)
    }

    const handleSaveFuelType = async (data: Partial<FuelType>) => {
        if (!supabase) throw new Error("Database not configured")

        if (selectedFuelType) {
            // Update existing
            const { error } = await supabase
                .from("fuel_types")
                .update(data)
                .eq("fuel_type_id", selectedFuelType.fuel_type_id)

            if (error) throw error
            toast.success("✅ Fuel Type Updated!", `${data.fuel_name} has been updated`)
        } else {
            // Create new
            const { error } = await supabase
                .from("fuel_types")
                .insert([data])

            if (error) throw error
            toast.success("✅ Fuel Type Created!", `${data.fuel_name} has been added`)
        }

        fetchFuelTypes()
    }

    const handleDeleteFuelType = async (fuelType: FuelType) => {
        if (!confirm(`Are you sure you want to delete "${fuelType.fuel_name}"?`)) return

        try {
            if (!supabase) throw new Error("Database not configured")

            const { error } = await supabase
                .from("fuel_types")
                .delete()
                .eq("fuel_type_id", fuelType.fuel_type_id)

            if (error) throw error
            toast.success("🗑️ Fuel Type Deleted", fuelType.fuel_name)
            fetchFuelTypes()
        } catch (error: unknown) {
            const errorMessage = error instanceof Error ? error.message : "Failed to delete"
            toast.error("Error", errorMessage)
        }
    }

    const handleToggleActive = async (fuelType: FuelType) => {
        try {
            if (!supabase) throw new Error("Database not configured")

            const newStatus = !fuelType.is_active
            const { error } = await supabase
                .from("fuel_types")
                .update({ is_active: newStatus })
                .eq("fuel_type_id", fuelType.fuel_type_id)

            if (error) throw error
            toast.success(newStatus ? "✅ Fuel Type Activated" : "⛔ Fuel Type Deactivated", fuelType.fuel_name)
            fetchFuelTypes()
        } catch (error: unknown) {
            const errorMessage = error instanceof Error ? error.message : "Failed to update"
            toast.error("Error", errorMessage)
        }
    }

    // Filter fuel types
    const filteredFuelTypes = fuelTypes.filter((ft) =>
        ft.fuel_name.toLowerCase().includes(searchQuery.toLowerCase()) ||
        ft.fuel_code?.toLowerCase().includes(searchQuery.toLowerCase())
    )

    // Stats
    const stats = {
        total: fuelTypes.length,
        active: fuelTypes.filter((ft) => ft.is_active).length,
        avgPrice: fuelTypes.length > 0
            ? fuelTypes.reduce((acc, ft) => acc + ft.price_per_liter, 0) / fuelTypes.length
            : 0,
    }

    return (
        <DashboardLayout>
            <div className="space-y-6">
                {/* Header */}
                <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
                    <div>
                        <h1 className="text-2xl font-bold text-gray-900 flex items-center gap-2">
                            🛢️ Fuel Types Management
                        </h1>
                        <p className="text-gray-500">Configure fuel types and pricing</p>
                    </div>
                    <div className="flex gap-2">
                        <Button variant="outline" onClick={fetchFuelTypes}>
                            <RefreshCw className="w-4 h-4" /> Refresh
                        </Button>
                        <Button onClick={() => { setSelectedFuelType(null); setShowFormModal(true) }}>
                            <Plus className="w-4 h-4" /> Add Fuel Type
                        </Button>
                    </div>
                </div>

                {/* Stats */}
                <div className="grid grid-cols-3 gap-4">
                    <Card>
                        <CardContent className="p-4">
                            <div className="flex items-center gap-3">
                                <div className="w-12 h-12 rounded-xl bg-blue-100 flex items-center justify-center">
                                    <Droplet className="w-6 h-6 text-blue-600" />
                                </div>
                                <div>
                                    <p className="text-2xl font-bold text-gray-900">{stats.total}</p>
                                    <p className="text-sm text-gray-500">Total Types</p>
                                </div>
                            </div>
                        </CardContent>
                    </Card>
                    <Card>
                        <CardContent className="p-4">
                            <div className="flex items-center gap-3">
                                <div className="w-12 h-12 rounded-xl bg-green-100 flex items-center justify-center">
                                    <CheckCircle className="w-6 h-6 text-green-600" />
                                </div>
                                <div>
                                    <p className="text-2xl font-bold text-gray-900">{stats.active}</p>
                                    <p className="text-sm text-gray-500">Active</p>
                                </div>
                            </div>
                        </CardContent>
                    </Card>
                    <Card>
                        <CardContent className="p-4">
                            <div className="flex items-center gap-3">
                                <div className="w-12 h-12 rounded-xl bg-purple-100 flex items-center justify-center">
                                    <DollarSign className="w-6 h-6 text-purple-600" />
                                </div>
                                <div>
                                    <p className="text-2xl font-bold text-gray-900">{formatCurrency(stats.avgPrice)}</p>
                                    <p className="text-sm text-gray-500">Avg Price/L</p>
                                </div>
                            </div>
                        </CardContent>
                    </Card>
                </div>

                {/* Search */}
                <Card>
                    <CardContent className="p-4">
                        <input
                            type="text"
                            value={searchQuery}
                            onChange={(e) => setSearchQuery(e.target.value)}
                            placeholder="🔍 Search fuel types by name or code..."
                            className="w-full px-4 py-3 border-2 border-gray-200 rounded-xl focus:border-blue-500 outline-none"
                        />
                    </CardContent>
                </Card>

                {/* Fuel Types Grid */}
                <Card>
                    <CardHeader>
                        <CardTitle>
                            <Droplet className="w-5 h-5 text-blue-600" />
                            📋 All Fuel Types ({filteredFuelTypes.length})
                        </CardTitle>
                    </CardHeader>
                    <CardContent>
                        {loading ? (
                            <div className="flex items-center justify-center py-12">
                                <Loader2 className="w-8 h-8 text-blue-600 animate-spin" />
                            </div>
                        ) : filteredFuelTypes.length === 0 ? (
                            <div className="text-center py-12 text-gray-500">
                                <Droplet className="w-12 h-12 mx-auto mb-4 text-gray-300" />
                                <p>{fuelTypes.length === 0 ? "No fuel types found. Add your first fuel type!" : "No fuel types match your search"}</p>
                            </div>
                        ) : (
                            <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">
                                {filteredFuelTypes.map((fuelType) => (
                                    <div
                                        key={fuelType.fuel_type_id}
                                        className="p-4 rounded-xl border border-gray-200 hover:border-gray-300 hover:shadow-md transition-all"
                                    >
                                        <div className="flex items-start justify-between mb-3">
                                            <div className="flex items-center gap-3">
                                                <div
                                                    className="w-12 h-12 rounded-xl flex items-center justify-center"
                                                    style={{ backgroundColor: (fuelType.color_code || "#3B82F6") + "20" }}
                                                >
                                                    <Droplet
                                                        className="w-6 h-6"
                                                        style={{ color: fuelType.color_code || "#3B82F6" }}
                                                    />
                                                </div>
                                                <div>
                                                    <h3 className="font-bold text-gray-900">{fuelType.fuel_name}</h3>
                                                    <p className="text-xs text-gray-500">Code: {fuelType.fuel_code}</p>
                                                </div>
                                            </div>
                                            <button
                                                onClick={() => handleToggleActive(fuelType)}
                                                className={`px-2 py-1 rounded-lg text-xs font-semibold ${fuelType.is_active
                                                        ? "bg-green-100 text-green-700"
                                                        : "bg-red-100 text-red-700"
                                                    }`}
                                            >
                                                {fuelType.is_active ? "Active" : "Inactive"}
                                            </button>
                                        </div>

                                        <div className="mb-3">
                                            <p className="text-2xl font-bold text-gray-900">
                                                {formatCurrency(fuelType.price_per_liter)}
                                                <span className="text-sm font-normal text-gray-500">/L</span>
                                            </p>
                                            {fuelType.description && (
                                                <p className="text-sm text-gray-500 mt-1">{fuelType.description}</p>
                                            )}
                                        </div>

                                        <div className="flex items-center gap-2 pt-3 border-t border-gray-100">
                                            <button
                                                onClick={() => { setSelectedFuelType(fuelType); setShowFormModal(true) }}
                                                className="flex-1 py-2 px-3 bg-blue-50 hover:bg-blue-100 text-blue-700 rounded-lg text-sm font-medium transition-colors flex items-center justify-center gap-1"
                                            >
                                                <Edit className="w-4 h-4" /> Edit
                                            </button>
                                            <button
                                                onClick={() => handleDeleteFuelType(fuelType)}
                                                className="py-2 px-3 bg-red-50 hover:bg-red-100 text-red-700 rounded-lg text-sm font-medium transition-colors"
                                            >
                                                <Trash2 className="w-4 h-4" />
                                            </button>
                                        </div>
                                    </div>
                                ))}
                            </div>
                        )}
                    </CardContent>
                </Card>
            </div>

            {/* Modal */}
            {showFormModal && (
                <FuelTypeFormModal
                    fuelType={selectedFuelType}
                    nextFuelTypeNumber={fuelTypes.length}
                    onSave={handleSaveFuelType}
                    onClose={() => { setShowFormModal(false); setSelectedFuelType(null) }}
                />
            )}
        </DashboardLayout>
    )
}
